#!/usr/bin/env bash
# Create site directory and Caddy config, then reload Caddy.
# Usage: sudo ./site-create.sh <domain> <site_path>
# Example: sudo ./site-create.sh example.com /var/www/example.com
# Env (optional): WEB_USER, CADDY_SITES_DIR, CADDYFILE, CADDY_RELOAD_CMD

set -e

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <domain> <site_path>" >&2
  exit 1
fi

DOMAIN="$1"
SITE_PATH="$2"
WEB_USER="${WEB_USER:-www-data}"
CADDY_SITES_DIR="${CADDY_SITES_DIR:-/etc/caddy/sites}"
CADDYFILE="${CADDYFILE:-/etc/caddy/Caddyfile}"

# Create site directory and set ownership
mkdir -p "$SITE_PATH"
if getent passwd "$WEB_USER" &>/dev/null; then
  chown "$WEB_USER:$WEB_USER" "$SITE_PATH"
fi

# Placeholder index.php so the site responds
if [[ ! -f "$SITE_PATH/index.php" ]]; then
  echo '<?php echo "<!DOCTYPE html><html><head><title>' "$DOMAIN" '</title></head><body><h1>Welcome to '"$DOMAIN"'</h1><p>PHP is working.</p></body></html>";' > "$SITE_PATH/index.php"
  [[ -n "$WEB_USER" ]] && getent passwd "$WEB_USER" &>/dev/null && chown "$WEB_USER:$WEB_USER" "$SITE_PATH/index.php"
fi

# Caddy snippet: FrankenPHP php_server with root
mkdir -p "$CADDY_SITES_DIR"
SAFE_DOMAIN="${DOMAIN//\*/_}"
CONF_FILE="$CADDY_SITES_DIR/${SAFE_DOMAIN}.conf"
cat > "$CONF_FILE" << EOF
# Generated by FrankenPHP Panel – do not edit manually
$DOMAIN {
	root * $SITE_PATH
	encode zstd gzip
	php_server
	file_server
}
EOF

# Reload Caddy
if [[ -n "$CADDY_RELOAD_CMD" ]]; then
  eval "$CADDY_RELOAD_CMD"
elif command -v caddy &>/dev/null && [[ -f "$CADDYFILE" ]]; then
  caddy reload --config "$CADDYFILE" 2>/dev/null || true
elif systemctl is-active --quiet caddy 2>/dev/null; then
  systemctl reload caddy 2>/dev/null || true
else
  echo "Warning: Caddy reload skipped (set CADDY_RELOAD_CMD or ensure caddy is running)." >&2
fi

echo "Site created: $DOMAIN -> $SITE_PATH"
