#!/usr/bin/env bash
# Create site directory and Caddy config, optionally install WordPress.
# Usage: sudo ./site-create.sh <domain> <site_path> [install_wordpress] [wp_title] [wp_admin_user] [wp_admin_password] [wp_admin_email]
# When install_wordpress=1, args 4–7 are WordPress site title, admin user, password, email (for wp core install).

set -e

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <domain> <site_path> [install_wordpress=0] [wp_title] [wp_admin_user] [wp_admin_password] [wp_admin_email]" >&2
  exit 1
fi

DOMAIN="$1"
SITE_PATH="$2"
INSTALL_WORDPRESS="${3:-0}"
WP_TITLE="${4:-}"
WP_ADMIN_USER="${5:-}"
WP_ADMIN_PASS="${6:-}"
WP_ADMIN_EMAIL="${7:-}"
WEB_USER="${WEB_USER:-www-data}"
CADDY_SITES_DIR="${CADDY_SITES_DIR:-/etc/caddy/sites}"
CADDYFILE="${CADDYFILE:-/etc/caddy/Caddyfile}"

# Create site directory and set ownership
mkdir -p "$SITE_PATH"
if getent passwd "$WEB_USER" &>/dev/null; then
  chown "$WEB_USER:$WEB_USER" "$SITE_PATH"
fi

# Placeholder index.php only for non-WordPress (WordPress will overwrite)
if [[ "$INSTALL_WORDPRESS" != "1" ]] && [[ ! -f "$SITE_PATH/index.php" ]]; then
  echo '<?php echo "<!DOCTYPE html><html><head><title>' "$DOMAIN" '</title></head><body><h1>Welcome to '"$DOMAIN"'</h1><p>PHP is working.</p></body></html>";' > "$SITE_PATH/index.php"
  [[ -n "$WEB_USER" ]] && getent passwd "$WEB_USER" &>/dev/null && chown "$WEB_USER:$WEB_USER" "$SITE_PATH/index.php"
fi

# --- WordPress: create DB, download WP, write wp-config ---
if [[ "$INSTALL_WORDPRESS" == "1" ]]; then
  if ! command -v mysql &>/dev/null; then
    echo "Error: mysql client not found. Install MariaDB/MySQL for WordPress." >&2
    exit 1
  fi
  # Sanitize domain to DB name (max 64 chars for MySQL)
  DB_NAME="wp_${DOMAIN//[^a-zA-Z0-9]/_}"
  DB_NAME="${DB_NAME:0:64}"
  DB_USER="${DB_NAME:0:32}"
  DB_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
  if mysql -e "CREATE DATABASE \`$DB_NAME\`; CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost'; FLUSH PRIVILEGES;" 2>/dev/null; then
    rm -f "$SITE_PATH/index.php"
    curl -sSLf "https://wordpress.org/latest.tar.gz" | tar xz -C /tmp
    mv /tmp/wordpress/* "$SITE_PATH/"
    rm -rf /tmp/wordpress
    SALTS=$(curl -sSL "https://api.wordpress.org/secret-key/1.1/salt/")
    {
      echo "<?php
define('DB_NAME', '$DB_NAME');
define('DB_USER', '$DB_USER');
define('DB_PASSWORD', '$DB_PASS');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');
"
      echo "$SALTS"
      echo "
\$table_prefix = 'wp_';
/* WordPress debug: log to wp-content/debug.log; set WP_DEBUG_DISPLAY to true only when fixing issues locally */
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
@ini_set('display_errors', 0);
define('SCRIPT_DEBUG', false);
if ( ! defined( 'ABSPATH' ) ) { define( 'ABSPATH', __DIR__ . '/' ); }
require_once ABSPATH . 'wp-settings.php';
"
    } > "$SITE_PATH/wp-config.php"
    if getent passwd "$WEB_USER" &>/dev/null; then
      chown -R "$WEB_USER:$WEB_USER" "$SITE_PATH"
    fi
    # Complete WordPress install with admin user, title, email (DB name/user are random and already in wp-config)
    if [[ -n "$WP_TITLE" && -n "$WP_ADMIN_USER" && -n "$WP_ADMIN_PASS" && -n "$WP_ADMIN_EMAIL" ]] && command -v wp &>/dev/null; then
      if wp core install --url="http://${DOMAIN}" --title="$WP_TITLE" --admin_user="$WP_ADMIN_USER" --admin_password="$WP_ADMIN_PASS" --admin_email="$WP_ADMIN_EMAIL" --path="$SITE_PATH" --skip-email 2>/dev/null; then
        if getent passwd "$WEB_USER" &>/dev/null; then
          chown -R "$WEB_USER:$WEB_USER" "$SITE_PATH"
        fi
        echo "WordPress installed. Log in at http://${DOMAIN}/wp-admin with $WP_ADMIN_USER and your chosen password."
      else
        echo "WordPress files and database are ready. Run the 5-minute setup at http://${DOMAIN}/wp-admin/install.php" >&2
      fi
    else
      echo "WordPress files and database are ready. Open http://${DOMAIN}/wp-admin/install.php to complete the 5-minute setup."
    fi
  else
    echo "Warning: Could not create MySQL database for WordPress. Install MariaDB and try again." >&2
  fi
fi

# Caddy snippet: FrankenPHP php_server with root
mkdir -p "$CADDY_SITES_DIR"
SAFE_DOMAIN="${DOMAIN//\*/_}"
CONF_FILE="$CADDY_SITES_DIR/${SAFE_DOMAIN}.conf"
cat > "$CONF_FILE" << EOF
# Generated by FrankenPHP Panel – do not edit manually
$DOMAIN {
	root * $SITE_PATH
	encode zstd gzip
	php_server
	file_server
}
EOF

# Reload Caddy/FrankenPHP so the new site is live
if [[ -n "$CADDY_RELOAD_CMD" ]]; then
  eval "$CADDY_RELOAD_CMD"
elif systemctl is-active --quiet frankenphp 2>/dev/null; then
  systemctl reload frankenphp 2>/dev/null || true
elif systemctl is-active --quiet caddy 2>/dev/null; then
  systemctl reload caddy 2>/dev/null || true
elif command -v frankenphp &>/dev/null && [[ -f "$CADDYFILE" ]]; then
  frankenphp reload --config "$CADDYFILE" --force 2>/dev/null || true
elif command -v caddy &>/dev/null && [[ -f "$CADDYFILE" ]]; then
  caddy reload --config "$CADDYFILE" 2>/dev/null || true
else
  echo "Warning: Caddy/FrankenPHP reload skipped (install FrankenPHP or set CADDY_RELOAD_CMD)." >&2
fi

echo "Site created: $DOMAIN -> $SITE_PATH"
